language: python
python:
  - 2.7

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh

install:
  - sudo pip install -e svn+http://pylibtiff.googlecode.com/svn/trunk/
  - sudo python setup.py build_ext install

script: nosetests -a '!slow'
